name: vikunja

include:
  - path:
      - ext/docker-compose-snippets/caddy.yaml
      - ext/docker-compose-snippets/reverse_proxy_override.yaml

services:
  vikunja:
    image: vikunja/vikunja
    hostname: proxy_target
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.ipn.rahulsalvi.com
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_DATABSE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_INTERFACE: :8080
      VIKUNJA_CORS_ENABLE: true
      VIKUNJA_SERVICE_JWTSECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret
    volumes:
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped

secrets:
  ts_authkey:
    file: ./ts_authkey.txt
  jwt_secret:
    file: ./jwt_secret.txt
