# vim: ft=yaml.docker-compose
name: vikunja

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml
  - ext/docker-compose-snippets/volume-backup-defaults.yaml

services:
  vikunja:
    image: ghcr.io/rahulsalvi/vikunja:latest
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.ipn.rahulsalvi.com
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_DATABSE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_INTERFACE: 127.0.0.1:8080
      VIKUNJA_CORS_ENABLE: true
      VIKUNJA_SERVICE_JWTSECRET_FILE: /run/secrets/jwt_secret
      VIKUNJA_AUTH_LOCAL_ENABLED: false
    secrets:
      - jwt_secret
      - oidc_client_id
      - oidc_client_secret
    volumes:
      - ./config.yml:/etc/vikunja/config.yml:ro
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

  backup:
    volumes:
      - ./files:/backup/files:ro
      - ./db:/backup/db:ro
    extends:
      file: ext/docker-compose-snippets/volume-backup.yaml
      service: aws-backup-default

secrets:
  ts_authkey:
    file: ./ts_authkey.txt
  jwt_secret:
    file: ./jwt_secret.txt
  oidc_client_id:
    file: ./oidc_client_id.txt
  oidc_client_secret:
    file: ./oidc_client_secret.txt
