# vim: ft=yaml.docker-compose
name: vikunja

include:
  - ext/docker-compose-snippets/tailscale-caddy.yaml
  - ext/docker-compose-snippets/simple-reverse-proxy.yaml

services:
  vikunja:
    image: ghcr.io/rahulsalvi/vikunja:latest
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.ipn.rahulsalvi.com
      VIKUNJA_DATABASE_TYPE: sqlite
      VIKUNJA_DATABSE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_INTERFACE: 127.0.0.1:8080
      VIKUNJA_CORS_ENABLE: true
      VIKUNJA_SERVICE_JWTSECRET_FILE: /run/secrets/jwt_secret
      VIKUNJA_AUTH_LOCAL_ENABLED: false
    secrets:
      - jwt_secret
      - oidc_client_id
      - oidc_client_secret
    volumes:
      - ./config.yml:/etc/vikunja/config.yml:ro
      - ./files:/app/vikunja/files
      - ./db:/db
    restart: unless-stopped
    extends:
      file: ext/docker-compose-snippets/tailscale-app-base.yaml
      service: tailscale-app-base

  backup:
    image: offen/docker-volume-backup:latest
    environment:
      BACKUP_CRON_EXPRESSION: "*/15 * * * *"
      AWS_S3_BUCKET_NAME_FILE: /run/secrets/aws_s3_bucket_name
      AWS_S3_PATH: ${COMPOSE_PROJECT_NAME}
      AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws_access_key_id
      AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/aws_secret_access_key
      AGE_PASSPHRASE_FILE: /run/secrets/age_passphrase
    secrets:
      - aws_s3_bucket_name
      - aws_access_key_id
      - aws_secret_access_key
      - age_passphrase
    restart: unless-stopped
    volumes:
      - ./files:/backup/files:ro
      - ./db:/backup/db:ro

secrets:
  ts_authkey:
    file: ./ts_authkey.txt
  jwt_secret:
    file: ./jwt_secret.txt
  oidc_client_id:
    file: ./oidc_client_id.txt
  oidc_client_secret:
    file: ./oidc_client_secret.txt
  aws_s3_bucket_name:
    file: ./aws_s3_bucket_name.txt
  aws_access_key_id:
    file: ./aws_access_key_id.txt
  aws_secret_access_key:
    file: ./aws_secret_access_key.txt
  age_passphrase:
    file: ./age_passphrase.txt
