auth:
  openid:
    enabled: true
    redirecturl: https://vikunja.ipn.rahulsalvi.com/auth/openid/
    providers:
      pocketid:
        name: Pocket-ID
        authurl: https://pocket-id.ipn.rahulsalvi.com
        clientid:
        clientsecret:
